### ISSUE TITLE
Deploy artifacts to Bintray or Maven Central

### ISSUE THREAD

**Issue by marshallpierce** [eseifert/gral#124]
This would make it simpler to depend on Gral (and spare you from maintaining your own repo).

Bintray has a gradle plugin to make it easy: https://github.com/bintray/gradle-bintray-plugin

If you want to go the maven central route, you'll need to follow the process here: http://central.sonatype.org/pages/ossrh-guide.html. You can see an example of the gradle bits here: https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir/src/4a4211b71c6e6f4c207174d255c9d41673a39dde/build.gradle?at=master

**Comment by seifertm** [comment]
Thanks for the helpful info.

You are making a valid point. It is easier to depend on GRAL, if its artefact can be found on Maven Central (albeit just a little easier :)
Since there have been other people making the same request, we will most likely to deploy GRAL on Maven Central. However, we decided to finish up the new version of GRAL (and most likely also Vectorgraphics2D) before the deployment.

**Comment by eseifert** [comment]
I just released version 0.11 of GRAL on Maven Central. It will be the main channel of distribution from now on.
